function [] = createReport( model, model_name, file_path )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here

model.result.dataset('dset1').run;
model.result('pg1').run;

model.result.report.create('rpt1', 'Report');
model.result.report('rpt1').set('level', 'brief');
model.result.report('rpt1').set('imagesize', 'medium');
model.result.report('rpt1').set('imagetype', 'jpeg');
model.result.report('rpt1').create('tp1', 'TitlePage');
model.result.report('rpt1').create('toc1', 'TableOfContents');
model.result.report('rpt1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec1').set('heading', 'Global Definitions');
model.result.report('rpt1').feature('sec1').create('root1', 'Model');
model.result.report('rpt1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec1').feature('sec1').set('heading', 'Parameters');
model.result.report('rpt1').feature('sec1').feature('sec1').create('param1', 'Parameter');
model.result.report('rpt1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').set('heading', 'Component 1');
model.result.report('rpt1').feature('sec2').create('comp1', 'ModelNode');
model.result.report('rpt1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').set('heading', 'Definitions');
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').set('heading', 'Selections');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').set('heading', 'Tumor');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').create('sel1', 'Selection');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec1').feature('sel1').set('noderef', 'sel1');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec2').set('heading', 'Magnets');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec2').create('sel1', 'Selection');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec2').feature('sel1').set('noderef', 'sel2');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec3').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec3').set('heading', 'Air Space');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec3').create('sel1', 'Selection');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec1').feature('sec3').feature('sel1').set('noderef', 'sel3');
model.result.report('rpt1').feature('sec2').feature('sec1').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').set('heading', 'Coordinate Systems');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').set('heading', 'Boundary System 1');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').create('csys1', 'CoordinateSystem');
model.result.report('rpt1').feature('sec2').feature('sec1').feature('sec2').feature('sec1').feature('csys1').set('noderef', 'sys1');
model.result.report('rpt1').feature('sec2').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec2').set('heading', 'Geometry 1');
model.result.report('rpt1').feature('sec2').feature('sec2').create('geom1', 'Geometry');
model.result.report('rpt1').feature('sec2').feature('sec2').feature('geom1').set('noderef', 'geom1');
model.result.report('rpt1').feature('sec2').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec3').set('heading', 'Materials');
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').set('heading', 'Tumor');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec1').feature('mat1').set('noderef', 'mat1');
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec2', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec2').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec2').set('heading', 'Magnet');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec2').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec2').feature('mat1').set('noderef', 'mat2');
model.result.report('rpt1').feature('sec2').feature('sec3').create('sec3', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec3').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec3').set('heading', 'Air');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec3').create('mat1', 'Material');
model.result.report('rpt1').feature('sec2').feature('sec3').feature('sec3').feature('mat1').set('noderef', 'mat3');
model.result.report('rpt1').feature('sec2').create('sec4', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec2').feature('sec4').set('heading', 'Magnetic Fields');
model.result.report('rpt1').feature('sec2').feature('sec4').create('phys1', 'Physics');
model.result.report('rpt1').feature('sec2').feature('sec4').feature('phys1').set('noderef', 'mf');
model.result.report('rpt1').feature('sec2').create('sec5', 'Section');
model.result.report('rpt1').feature('sec2').feature('sec5').set('source', 'firstchild');
model.result.report('rpt1').feature('sec2').feature('sec5').set('heading', 'Mesh 1');
model.result.report('rpt1').feature('sec2').feature('sec5').create('mesh1', 'Mesh');
model.result.report('rpt1').feature('sec2').feature('sec5').feature('mesh1').set('noderef', 'mesh1');
model.result.report('rpt1').create('sec3', 'Section');
model.result.report('rpt1').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec3').set('heading', 'Study 1');
model.result.report('rpt1').feature('sec3').create('std1', 'Study');
model.result.report('rpt1').feature('sec3').feature('std1').set('noderef', 'std1');
model.result.report('rpt1').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').set('heading', 'Results');
model.result.report('rpt1').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec1').set('heading', 'Data Sets');
model.result.report('rpt1').feature('sec4').feature('sec1').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').set('heading', 'Study 1/Solution 1');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').create('dset1', 'DataSet');
model.result.report('rpt1').feature('sec4').feature('sec1').feature('sec1').feature('dset1').set('noderef', 'dset1');
model.result.report('rpt1').feature('sec4').create('sec2', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec2').set('heading', 'Derived Values');
model.result.report('rpt1').feature('sec4').feature('sec2').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').set('heading', 'Volume Average 1');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').create('num1', 'DerivedValues');
model.result.report('rpt1').feature('sec4').feature('sec2').feature('sec1').feature('num1').set('noderef', 'av1');
model.result.report('rpt1').feature('sec4').create('sec3', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec3').set('heading', 'Tables');
model.result.report('rpt1').feature('sec4').feature('sec3').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').set('heading', 'Table 1');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').create('mtbl1', 'Table');
model.result.report('rpt1').feature('sec4').feature('sec3').feature('sec1').feature('mtbl1').set('noderef', 'tbl1');
model.result.report('rpt1').feature('sec4').create('sec4', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec4').set('source', 'custom');
model.result.report('rpt1').feature('sec4').feature('sec4').set('heading', 'Plot Groups');
model.result.report('rpt1').feature('sec4').feature('sec4').create('sec1', 'Section');
model.result.report('rpt1').feature('sec4').feature('sec4').feature('sec1').set('source', 'firstchild');
model.result.report('rpt1').feature('sec4').feature('sec4').feature('sec1').set('heading', 'Magnetic Flux Density Norm (mf)');
model.result.report('rpt1').feature('sec4').feature('sec4').feature('sec1').create('pg1', 'PlotGroup');
model.result.report('rpt1').feature('sec4').feature('sec4').feature('sec1').feature('pg1').set('noderef', 'pg1');

model.result.report('rpt1').feature('tp1').set('title', model_name );
model.result.report('rpt1').feature('tp1').set('author', 'Serxhio Rira');
model.result.report('rpt1').feature('tp1').set('summary', 'In this Project, magnet parameters will be optimized in order to find the optimum magnet array that maximizes the average mean magnetic flux density in a tumor model.');
model.result.report('rpt1').set('format', 'docx');
file_name = strcat( strcat( '\',model_name), '.docx');
file_path = strcat( file_path, file_name);
model.result.report('rpt1').set('filename', file_path);

model.result.report('rpt1').run;
model.result.report('rpt1').set('openwhenfinished', true);

model.result().report('rpt1').run();
end

